---
title: Flexdashboard y htmlwidgets
output: html_document
---

```{r, child="_yoshi-TOC.Rmd"}
```

<style>
  /* Fix embedded video width for mobile */
  @media (max-width: 767px) {
    iframe { max-width: 90vw; }
  }
</style>

## Video para la sesión 5

<iframe width="560" height="315" src="https://www.youtube.com/embed/5DX_xL_zq2I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Flexdashboard

En la siguiente sesión, exploraremos el `sidebar` que es posible
crear para el dashboard, con el cual podremos manipular el input
que deseamos para los gráficos que presentaremos usando los paquetes
**htmlwidgets** y **shiny**.

## htmlwidgets

En esta sesión, empleamos **siete widgets** _importados_ de librerías
de **JavaScript** gracias al paquete **htmlwidgets**.<br>
Existen más **widgets** disponibles en **R**, así que podrían
buscar más ejemplos de los vistos en clase.

Todavía no exploraremos la funcionalidad del paquete **htmlwidgets**
para poder crear **nuestro propio widget**, ya que aquello lo realizaremos
en la última sesión del taller, después de haber aprendido lo básico
del lenguaje de programación **JavaScript**.

## Tarea

Para la siguiente sesión, deben haber creado un dashboard en el cual
empleen al menos **tres** de los widgets presentados en clase, con el fin
de explorar algún dataset (o datasets) que usteden hayan escogido.

El objetivo de la tarea es que en la siguiente sesión, podamos potenciar
el dashboard creado, convirtiéndolo en una aplicación web vía el uso
del paquete **Shiny**.

Aquel paquete nos permitirá condicionar la ejecución de cierto código 
(sea de R, Python, JavaScript, etc), en función de la interacción del usuario
con ciertos elementos del sitio web que crearemos.

Ejemplos de proyectos creados con el paquete **Shiny**:

- <https://dreamrs.shinyapps.io/memory-hex/>
- <https://shiny.rstudio.com/gallery/kmeans-example.html>