---
title: Sesión 5
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(DT)
library(flexdashboard)
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

# Flexdashboard

## {data-width=600}

### Sección c11 {data-height=300}

<style>
  #sección-c11 > div {
    overflow: auto;
  }
</style>

```{r instalaciones, eval=FALSE}
# Creación de dashboards con R Markdown
install.packages('flexdashboard')

# Paquete para tablas interactivas
install.packages('DT')
```

### Sección c12 {data-height=700}

```{r, echo = FALSE}
#options(DT.options = list(scrollY="100vh"))

datatable(iris,
  extensions = "Buttons",
  options = list(
    dom="Bfrtip",
    buttons=c("copy","print","csv")
  )
)
```

## {data-width=400}

### Mensaje para valueBox {data-height=600}

```{r, echo = FALSE}
value <- 13
valueBox(
  value, icon = "fa-trash", href="#htmlwidgets", # solo dirige a páginas
  color = ifelse(value > 10, "warning", "primary") # succes, danger
)
```

### Sección c23 {data-height=400}

```{r, echo = FALSE}
level <- 42
gauge(level, min=0, max=100, symbol="%",
      gaugeSectors(success=c(90,100),
                   warning=c(70,89),
                   danger=c(0,69))
)
```

# htmlwidgets {data-icon=fa-fighter-jet}

## {.tabset .tabset-fade}

### Leaflet

```{r, echo = FALSE}
library(leaflet)

m <- leaflet() %>% addTiles()
m
```

### DT
y