---
title: "HTML notebook"
author: "Lucio Cornejo"
date: "`r Sys.Date()`"
params: 
  anio: 1935
  HTML: TRUE
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
    theme: cerulean
    hightlight: tango 
  pdf_document:
    toc: true
    latex_engine: xelatex
# rmarkdown::render("1-parametrizacion-basica.Rmd",output_format = "all")   
#
# install.packages('shiny')
# rmarkdown::render("1-parametrizacion-basica.Rmd",params = "ask")
#
# click "knit with parameters"
---

```{r cargar-data, include=FALSE}
# Base de datos usada para crear el data frame "temperaturas":
# nottem (Average Monthly Temperatures at Nottingham, 1920-1939)
temperaturas <- readxl::read_excel(file.choose())
```

```{r escoger-anio,echo=FALSE}
# Años posibles: 1920 a 1939
anio <- params$anio   ################
```

## Año `r anio`  

### Temperaturas mensuales promedio en _Nottingham_

<center>
```{r diagrama-de-barras,echo = FALSE}
temperatura_anual <- temperaturas[temperaturas$anio == anio,]
temperatura_anual <- unlist(temperatura_anual)[-1]

barplot(height = temperatura_anual, names = 1:12,
       xlab = "Mes", ylab = "Temperatura promedio", col="skyblue")
```
</center>

### Conclusiones

```{r mes-max-min-temperatura, include=FALSE}
mes_max_temperatura <- colnames(temperaturas)[1+which(temperatura_anual == max(temperatura_anual))]
mes_min_temperatura <- colnames(temperaturas)[1+which(temperatura_anual == min(temperatura_anual))]
```

- En `r mes_max_temperatura`, se registró la temperatura promedio mensual máxima
del año `r anio`.

- En `r mes_min_temperatura`, se registró la temperatura promedio mensual mínima
del año `r anio`.

<br>