---
runtime: shiny
output: html_document
---

```{r setup, include = FALSE}
library(shiny)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# ui

fluidPage(
  titlePanel("Hello Shiny!"),

  sidebarLayout(

    sidebarPanel(
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30
                  )
    ),

    mainPanel(
      plotOutput(outputId = "distPlot")
    )
  )
)
```

```{r}
# server

output$distPlot <- renderPlot({
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times"
        )

})
```

```{js codigo-de-JavaScript}
// Extender el grosor de la UI para que se parezca al del ejemplo
let ui = document.querySelector('div.container-fluid.main-container');
ui.style.maxWidth = "100vw";
```